'use client'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import 'aos/dist/aos.css'
import AOSInit from "./[components]/AOSInit";
import HeroContact from "./[components]/HeroContact";
import ScrollBtn from "./[components]/ScrollBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metatitle = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: "--font-Inter-sans",
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AOSInit/>
        <ThemeProvider attribute="class">
        <Header/>
        {children}
        <ScrollBtn/>
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
